name: Autolink Issue

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add an issue link
        uses: tkt-actions/add-issue-links@v1.7.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: 'i'
          position: 'top'
          resolve: 'true'
